/* dependency-cruiser config — enforces module boundaries
 * Generated by code-craftsman skill
 * Adapt domain folders to your project structure
 */
module.exports = {
  forbidden: [
    {
      name: 'no-cross-domain-imports',
      severity: 'error',
      comment: 'Domains should not import each other directly. Use shared/ or events.',
      from: { path: '^src/(billing|orders|identity|payments)/' },
      to: {
        path: '^src/(billing|orders|identity|payments)/',
        pathNot: ['^src/$1/']
      }
    },
    {
      name: 'no-circular',
      severity: 'error',
      comment: 'Circular dependencies are forbidden — refactor.',
      from: {},
      to: { circular: true }
    },
    {
      name: 'no-orphans',
      severity: 'warn',
      comment: 'Files not imported anywhere may be dead code.',
      from: {
        orphan: true,
        pathNot: [
          '(^|/)\\.[^/]+\\.(js|cjs|mjs|ts|tsx|json)$',
          '\\.d\\.ts$',
          '(^|/)tsconfig\\.json$',
          '(^|/)(babel|webpack)\\.config\\.(js|cjs|mjs|ts|json)$',
          '\\.test\\.(js|ts|tsx)$',
          '\\.spec\\.(js|ts|tsx)$'
        ]
      },
      to: {}
    },
    {
      name: 'no-deprecated-core',
      severity: 'warn',
      comment: 'Avoid deprecated Node core modules.',
      from: {},
      to: { dependencyTypes: ['core'], path: '^(punycode|domain|sys)$' }
    },
    {
      name: 'not-to-spec',
      severity: 'error',
      comment: 'Production code must not depend on test code.',
      from: { pathNot: '\\.(spec|test)\\.(js|ts|tsx)$' },
      to: { path: '\\.(spec|test)\\.(js|ts|tsx)$' }
    },
    {
      name: 'not-to-dev-dep',
      severity: 'error',
      comment: 'Production code must not depend on devDependencies.',
      from: { path: '^src', pathNot: '\\.(spec|test)\\.(js|ts|tsx)$' },
      to: { dependencyTypes: ['npm-dev'] }
    }
  ],
  options: {
    doNotFollow: { path: 'node_modules' },
    tsConfig: { fileName: './tsconfig.json' },
    enhancedResolveOptions: {
      exportsFields: ['exports'],
      conditionNames: ['import', 'require', 'node', 'default']
    },
    reporterOptions: {
      dot: { collapsePattern: 'node_modules/[^/]+' },
      archi: {
        collapsePattern: '^(packages|src|lib)/[^/]+|node_modules/[^/]+'
      }
    }
  }
}
